# Generated by Django 3.1.7 on 2021-03-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210320_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('email', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=80)),
                ('state', models.CharField(default='', max_length=80)),
                ('zip_code', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
